#' Mark Required Fields with a Prefix
#'
#' @param p Character vector. All fields to be processed.
#' @param r Character vector. Fields that are required.
#' @param req_str Character. Prefix to mark required fields. Defaults to `"* "`.
#'
#' @return A character vector with required fields prefixed and ordered to
#'   appear before non-required fields.
#'
#' @examples
#' # Mark required fields with a prefix
#' add_required_str(c("Name", "Id", "Age"), c("Id", "Name"))
#'
#' @export
add_required_str <- function(p, r, req_str = "* ") {
    if (!is.character(p)) {
        stop("The 'p' argument must be a character vector.")
    }

    .validate_character_scalar(req_str)

    out <- vapply(p, function(x) {
        if (x %in% r) {
            paste0(req_str, x)
        } else {
            x
        }
    }, character(1), USE.NAMES = FALSE)

    out
}

#' Retrieve Enum Values from an API
#'
#' This function retrieves the values of a specified enum from an API by
#' invoking the corresponding client function.
#'
#' @param client List. The API client, typically generated by `create_client`,
#'   containing functions for API operations.
#' @param enum_name Character. The name of the enum to retrieve.
#' @param enum_prefix Character. Optional. The prefix used in the client for
#'   enum functions. Defaults to `"get__enums__"`.
#'
#' @return The values of the specified enum.
#'
#' @examples
#' # Create API client with mock api_key
#' client <- create_client(extract_api(), api_key = "ABCD")
#'
#' # Retrieve enum values from the API client (requires credentials to work)
#' try(
#'     platform_models <- get_enum(client, enum_name = "platform_models")
#' )
#'
#' @export
get_enum <- function(client, enum_name, enum_prefix = "get__enums__") {
    .is_client(client)
    .validate_character_scalar(enum_name)
    .validate_character_scalar(enum_prefix)

    enum_string <- paste0(enum_prefix, enum_name)
    if (is.null(client[[enum_string]])) {
        stop(sprintf("%s not found in client.", enum_string))
    }

    client[[enum_string]]()
}

#' Parse Enum into a Formatted String
#'
#' This function parses an enum, represented as a data frame or character
#' vector, into a formatted string for display or further use.
#'
#' @param enum Data frame or character vector. The enum to parse. If a data
#'   frame, its rows are concatenated into strings. If a character vector, its
#'   elements are joined with newlines.
#' @param sep Character. If enum has multiple fields, they will be pasted into a
#'   single string using this separator. Defaults to `--`
#'
#' @return A single string representing the parsed enum. Rows are joined by
#'   newlines and multiple enum fields are joined by `sep`.
#'
#' @examples
#' # Parse an enum as a data frame
#' df_enum <- data.frame(key = c("A", "B"), value = c("1", "2"))
#' parse_enum(df_enum)
#'
#' # Parse an enum as a character vector
#' vec_enum <- c("A", "B", "C")
#' parse_enum(vec_enum)
#'
#' @export
parse_enum <- function(enum, sep = "--") {
    # If enum is a data frame
    if (is.data.frame(enum)) {
        # Explicit return of edge cases
        if (nrow(enum) == 0 || ncol(enum) == 0) {
            return("")
        }
        # Create a data frame from nested values
        parsed_str <- apply(
            enum,
            1,
            \(row) paste0(str_trim(row), collapse = sep)
        )
        # Paste together in a single string
        parsed_str <- paste(parsed_str, collapse = "\n")
    } else if (is.character(enum)) {
        parsed_str <- paste(enum, collapse = "\n")
    } else {
        stop("Unknown type of enum returned for parsing.")
    }
    parsed_str
}

#' Filter Out ID Fields from a Character Vector
#'
#' This function filters out elements from a character vector that match a
#' specified regular expression pattern, removing ID fields.
#'
#' @param x Character vector. The input vector to filter.
#' @param pattern Character. Optional. A regular expression pattern for matching
#' ID fields to exclude. Defaults to
#' `"(?<!policy_)accession_id|provisional_id"`, which removes accession
#' IDs and provisional IDs, but not policy accession ID.
#'
#' @return A character vector with elements matching the pattern removed.
#'
#' @examples
#' # Filter out default ID fields
#' fields <- c("accession_id", "policy_accession_id", "name", "provisional_id")
#' filter_id_fields(fields)
#'
#' # Filter with a custom pattern
#' filter_id_fields(fields, pattern = "_id")
#'
#' @export
filter_id_fields <- function(x, pattern = NULL) {
    if (!is.character(x)) stop("'x' must be a character vector.")
    if (!is.null(pattern)) .validate_character_scalar(pattern)

    if (is.null(pattern)) pattern <- "(?<!policy_)accession_id|provisional_id"
    x[!grepl(pattern, x, perl = TRUE)]
}

#' Retrieve Request schemas from an API Specification
#'
#' This function extracts and returns schemas related to requests from the API
#' specification.
#'
#' @param api List. The API specification, typically containing a `components`
#'   element with nested `schemas`.
#'
#' @return A list of schemas whose names contain "Request", filtered from the
#'   `schemas` element of the API specification.
#'
#' @examples
#' # Extract request schemas from an API specification
#' request_schemas <- get_schemas(extract_api())
#'
#' @export
get_schemas <- function(api) {
    if (!is.list(api)) {
        stop("The 'api' argument must be a list.")
    }

    if (!"components" %in% names(api)) {
        stop("The 'api' list must contain an element named 'components'.")
    }

    if (!is.list(api$components)) {
        stop("The 'components' element within 'api' must be a list.")
    }

    if (!"schemas" %in% names(api$components)) {
        stop(
            "The 'api$components' list must contain an element named 'schemas'."
        )
    }

    schemas <- Filter(Negate(is.null), api$components$schemas)
    schemas <- schemas[grepl("Request", names(schemas))]
    schemas
}

#' Extract and Format Properties from a Schema
#'
#' This function extracts property names from a schema, optionally filters out
#' ID fields, and applies formatting such as marking required fields and
#' prettifying the labels.
#'
#' @param schema List. The schema containing `properties` and `required` fields.
#' @param filter_ids Logical. Whether to filter out ID fields from the
#'   properties. Defaults to `TRUE`.
#'
#' @return A character vector of formatted property names and indications of
#'   required fields.
#'
#' @examples
#' schemas <- get_schemas(extract_api())
#'
#' # Extract and format properties from a schema
#' get_properties(schemas[[5]])
#'
#' # Extract properties without filtering ID fields
#' get_properties(schemas[[6]], filter_ids = FALSE)
#'
#' @export
get_properties <- function(schema, filter_ids = TRUE) {
    if (!is.list(schema) || is.null(names(schema))) {
        stop("'schema' must be a named list.")
    }

    if (!"properties" %in% names(schema)) {
        stop("No 'properties' key in schema.")
    }

    .validate_logical_scalar(filter_ids, "filter_ids")

    required <- schema$required
    out <- names(schema$properties)
    if (filter_ids) out <- filter_id_fields(out)
    out <- add_required_str(out, required)
    out <- api_name_to_label(out)
    out
}

#' Count the number of words in text
#'
#' Compute the number of words in each element of a character vector using
#' non-word separators.
#'
#' @param text A character vector with text.
#'
#' @return An integer vector giving the number of words per element of
#'   \code{text}.
#'
#' @examples
#' get_word_number(c("one two", "three four five"))
#'
#' @export
get_word_number <- function(text) {
    if (!is.character(text)) {
        stop("'text' must be a character vector.")
    }

    no_ws <- gsub("\\s+", "", text)
    single_word_str <- nchar(text) == nchar(no_ws)
    empty_str <- nchar(no_ws) == 0

    result <- lengths(gregexpr("\\W+", text)) + 1L
    result[single_word_str] <- 1L
    result[empty_str] <- 0L

    result
}

#' Count the number of sentences in text
#'
#' Count how many sentences are in a character string, based on terminal
#' punctuation marks \code{.}, \code{!}, or \code{?} following an
#' alphanumeric character. If there is no punctuation character at the end, it
#' will still count it as another sentence.
#'
#' @param text A character vector.
#'
#' @return An integer scalar giving the number of sentences in \code{text}.
#'
#' @examples
#' get_sentence_number("First sentence. Second sentence? Third!")
#'
#' @export
get_sentence_number <- function(text) {
    if (!is.character(text) || length(text) < 1)  {
        stop("'text' must be a character vector.")
    }

    matches <- gregexpr("[[:alnum:]][.!?]", text)
    match_counts <- lengths(lapply(matches, function(x) x[x != -1]))

    no_ws <- gsub("\\s+", "", text)
    has_content <- nchar(no_ws) > 0

    needs_extra <- has_content & !grepl("[.!?]$", text)
    result <- match_counts + as.integer(needs_extra)

    as.integer(result)
}

#' Convert NA Values to Empty Lists
#'
#' Replaces \code{NA} values in a list with empty lists, preserving the original
#' structure of the list. Doesn't work on nested lists.
#'
#' @param l A list containing elements that may include \code{NA} values.
#'
#' @return A list where any \code{NA} values have been replaced with empty
#'   lists.
#'
#' @examples
#' input_list <- list(1, NA, "text", NA)
#' na_to_empty_list(input_list)
#'
#' @export
na_to_empty_list <- function(l) {
    if (!is.list(l) && !is.null(l) && !is.vector(l)) {
        stop("The argument 'l' must be a list, vector or NULL.")
    }

    lapply(l, function(x) {
        if (all(is.na(x))) {
            list()
        } else {
            x
        }
    })
}

#' Check if an object is a non-complex atomic scalar.
#'
#' An atomic scalar is defined as an atomic vector of length exactly
#' one, excluding complex numbers.
#'
#' @param x An object to be tested.
#'
#' @return A logical value: \code{TRUE} if \code{x} is a non-complex
#'   atomic scalar, \code{FALSE} otherwise.
#'
#' @examples
#' # Returns TRUE for simple, single values
#' .is_scalar(5L)
#' .is_scalar("hello")
#' .is_scalar(TRUE)
#' # Returns FALSE for vectors, lists, or complex numbers
#' .is_scalar(c(1, 2))
#' .is_scalar(list(1))
#' .is_scalar(1 + 1i)
#'
#' @keywords internal
.is_scalar <- function(x) {
    is.atomic(x) && length(x) == 1L && !is.complex(x)
}

#' Validate that an object is a non-empty character scalar.
#'
#' Checks if \code{x} is a character vector with a length of exactly one, is not
#' \code{NA}, and contains at least one character (i.e., not an empty string,
#' \code{""}). If the check fails, the function stops execution and reports an
#' error using the variable name.
#'
#' @param x An object to be tested.
#' @param varname A character string specifying the name of the variable being
#'   checked, used in the error message. If \code{NULL}, the variable name is taken
#'   from the name of variable being tested. Defaults to \code{NULL}
#'
#' @return Returns \code{TRUE} if the validation succeeds, otherwise stops
#'   execution with an error.
#'
#' @examples
#' # Returns TRUE silently
#' .validate_character_scalar("valid_string", "input_arg")
#'
#' # Throws an error for an empty string
#' tryCatch(
#'     .validate_character_scalar("", "empty_arg"),
#'     error = function(e) message(e$message)
#' )
#'
#' @keywords internal
.validate_character_scalar <- function(x, varname = NULL) {
    if (is.null(varname)) {
        varname_expr <- substitute(x)
        varname <- deparse(varname_expr)
        val <- x
    } else {
        val <- x
    }
    if (!is.character(val) || !.is_scalar(val) || !nzchar(val) || is.na(val)) {
        stop(
            sprintf("%s must be a non-empty character scalar.", varname)
        )
    }
    TRUE
}

#' Validate that an object is a non-missing logical scalar.
#'
#' Checks if \code{x} is a logical vector with a length of exactly one and is
#' not \code{NA}. If the check fails, the function stops execution and reports
#' an error using the variable name.
#'
#' @param x An object to be tested.
#' @param varname A character string specifying the name of the variable being
#'   checked, used in the error message.  If \code{NULL}, the variable name is
#'   taken from the name of variable being tested. Defaults to \code{NULL}
#'
#' @return Returns \code{TRUE} if the validation succeeds, otherwise stops
#'   execution with an error.
#'
#' @examples
#' # Returns TRUE silently
#' .validate_logical_scalar(TRUE, "input_check")
#'
#' # Throws an error for a logical NA
#' tryCatch(
#'     .validate_logical_scalar(NA, "na_arg"),
#'     error = function(e) message(e$message)
#' )
#'
#' @keywords internal
.validate_logical_scalar <- function(x, varname = NULL) {
    if (is.null(varname)) {
        varname_expr <- substitute(x)
        varname <- deparse(varname_expr)
        val <- x
    } else {
        val <- x
    }

    if (!is.logical(val) || !.is_scalar(val) || is.na(val)) {
        stop(
            sprintf("%s must be a non-empty logical scalar or NULL.", varname)
        )
    }
    TRUE
}

#' Validate that an object is an API client.
#'
#' Checks that \code{client} is a list where every element is a function.
#' Additionally, it verifies that the name of each function starts with a valid
#' HTTP method (e.g., \code{get_}, \code{post_}, etc.). It stops execution with
#' an error if any of the checks fail.
#'
#' @param client An object to be tested, expected to be a list of functions.
#'
#' @return Returns \code{TRUE} if the validation succeeds, otherwise stops
#'   execution with an error.
#'
#' @importFrom stringr str_split_fixed
#'
#' @examples
#' # Returns TRUE silently for a valid client structure
#' valid_client <- list(
#'     get_resource = function(...) "GET",
#'     post_data = function(...) "POST"
#' )
#' .is_client(valid_client)
#'
#' @keywords internal
.is_client <- function(client) {
    if (!is.list(client) || length(client) < 1) {
        stop("'client' must be a non-empty list.")
    }

    if (!all(vapply(client, is.function, FUN.VALUE = logical(1)))) {
        stop("'client' must be a list of functions.")
    }

    http_methods <- as.character(
        str_split_fixed(names(client), pattern = "_", n = 2)[, 1]
    )

    if (!all(vapply(http_methods, is_valid_http_method, logical(1)))) {
        stop("'client' function names must start with valid http method name.")
    }

    TRUE
}
