#' Mark Required Fields with a Prefix
#'
#' @param p Character vector. All fields to be processed.
#' @param r Character vector. Fields that are required.
#' @param req_str Character. Prefix to mark required fields.
#' Defaults to `"* "`.
#'
#' @return A character vector with required fields prefixed and ordered to
#' appear before non-required fields.
#'
#' @examples
#' # Mark required fields with a prefix
#' add_required_str(c("Name", "Id", "Age"), c("Id", "Name"))
#'
#' @export
add_required_str <- function(p, r, req_str = "* ") {
    if (!is.character(req_str) || length(req_str) != 1) {
        stop("'req_str' must be a scalar character")
    }

    pos_req <- which(p %in% r)
    pos_other <- which(!p %in% r)
    ordering <- c(pos_req, pos_other)

    out <- vapply(p, function(x) {
        if (x %in% r) {
            paste0(req_str, x)
        } else {
            x
        }
    }, character(1), USE.NAMES = FALSE)

    return(out)
}

#' Retrieve Enum Values from an API
#'
#' This function retrieves the values of a specified enum from an API by
#' invoking the corresponding client function.
#'
#' @param client List. The API client, typically generated by `create_client`,
#' containing functions for API operations.
#' @param enum_name Character. The name of the enum to retrieve.
#' @param enum_prefix Character. Optional. The prefix used in the client for
#' enum functions. Defaults to `"get__enums_"`.
#'
#' @return The values of the specified enum.
#'
#' @examples
#' # Create API client with mock api_key
#' client <- create_client(extract_api(), api_key = "ABCD")
#'
#' # Retrieve enum values from the API client (requires credentials to work)
#' try(
#'     platform_models <- get_enum(client, enum_name = "platform_models")
#' )
#'
#' @export
get_enum <- function(client, enum_name, enum_prefix = "get__enums_") {
    enum_string <- paste0(enum_prefix, enum_name)
    if (is.null(client[[enum_string]])) {
        stop(sprintf("%s not found in client", enum_string))
    }

    return(client[[enum_string]]())
}

#' Parse Enum into a Formatted String
#'
#' This function parses an enum, represented as a data frame or character
#' vector, into a formatted string for display or further use.
#'
#' @param enum Data frame or character vector. The enum to parse. If a data
#'   frame, its rows are concatenated into strings. If a character vector, its
#'   elements are joined with newlines.
#' @param sep Character. If enum has multiple fields, they will be pasted into a
#'   single string using this separator. Defaults to `--`
#'
#' @return A single string representing the parsed enum. Rows are joined by
#'   newlines and multiple enum fields are joined by `sep`.
#'
#' @examples
#' # Parse an enum as a data frame
#' df_enum <- data.frame(key = c("A", "B"), value = c("1", "2"))
#' parse_enum(df_enum)
#'
#' # Parse an enum as a character vector
#' vec_enum <- c("A", "B", "C")
#' parse_enum(vec_enum)
#'
#' @export
parse_enum <- function(enum, sep = "--") {
    # If enum is a data frame
    if (is.data.frame(enum)) {
        # Explicit return of edge cases
        if (nrow(enum) == 0 || ncol(enum) == 0) {
            return("")
        }
        # Create a data frame from nested values
        parsed_str <- apply(
            enum,
            1,
            \(row) paste0(str_trim(row), collapse = sep)
        )
        # Paste together in a single string
        parsed_str <- paste(parsed_str, collapse = "\n")
    } else if (is.character(enum)) {
        parsed_str <- paste(enum, collapse = "\n")
    } else {
        stop("Unknown type of enum returned for parsing.")
    }
    return(parsed_str)
}

#' Filter Out ID Fields from a Character Vector
#'
#' This function filters out elements from a character vector that match a
#' specified regular expression pattern, removing ID fields.
#'
#' @param x Character vector. The input vector to filter.
#' @param pattern Character. Optional. A regular expression pattern for matching
#' ID fields to exclude. Defaults to
#' `"(?<!policy_)accession_id|provisional_id"`, which removes accession
#' IDs and provisional IDs, but not policy accession ID.
#'
#' @return A character vector with elements matching the pattern removed.
#'
#' @examples
#' # Filter out default ID fields
#' fields <- c("accession_id", "policy_accession_id", "name", "provisional_id")
#' filter_id_fields(fields)
#'
#' # Filter with a custom pattern
#' filter_id_fields(fields, pattern = "_id")
#'
#' @export
filter_id_fields <- function(x, pattern = NULL) {
    if (!is.character(x)) stop("'x' must be a character vector.")

    if (is.null(pattern)) pattern <- "(?<!policy_)accession_id|provisional_id"
    return(x[!grepl(pattern, x, perl = TRUE)])
}

#' Retrieve Request Schemas from an API Specification
#'
#' This function extracts and returns schemas related to requests from the API
#' specification.
#'
#' @param api List. The API specification, typically containing a `components`
#' element with nested `schemas`.
#'
#' @return A list of schemas whose names contain "Request", filtered from the
#' `schemas` element of the API specification.
#'
#' @examples
#' # Extract request schemas from an API specification
#' request_schemas <- get_schemas(extract_api())
#'
#' @export
get_schemas <- function(api) {
    schemas <- Filter(Negate(is.null), api$components$schemas)
    schemas <- schemas[grepl("Request", names(schemas))]
    return(schemas)
}

#' Extract and Format Properties from a Schema
#'
#' This function extracts property names from a schema, optionally filters out
#' ID fields, and applies formatting such as marking required fields and
#' prettifying the labels.
#'
#' @param schema List. The schema containing `properties` and `required` fields.
#' @param filter_ids Logical. Whether to filter out ID fields from the
#'   properties. Defaults to `TRUE`.
#'
#' @return A character vector of formatted property names and indications of
#'   required fields.
#'
#' @examples
#' schemas <- get_schemas(extract_api())
#'
#' # Extract and format properties from a schema
#' get_properties(schemas[[5]])
#'
#' # Extract properties without filtering ID fields
#' get_properties(schemas[[6]], filter_ids = FALSE)
#'
#' @export
get_properties <- function(schema, filter_ids = TRUE) {
    if (!is.list(schema) || is.null(names(schema))) {
        stop("'schema' must be a named list")
    }

    if (!"properties" %in% names(schema)) {
        stop("No 'properties' key in schema.")
    }

    required <- schema$required
    out <- names(schema$properties)
    if (filter_ids) out <- filter_id_fields(out)
    out <- add_required_str(out, required)
    out <- api_name_to_label(out)
    return(out)
}
